baseurl = "https://divan.dev/"
languageCode = "en-us"
title = "divan's blog"
pygmentsCodeFences = true
[params]
	github = "divan"
	twitter = "idanyliuk"
	contact = "mailto:ivan.daniluk@gmail.com"
	bio = "Gopher. Public speaker."
	subtitle = "random thoughts on Go and software design"
	disqus = "divanblog"
	ga_api_key = "UA-70805978-1"
	avatar = "/images/avatar.jpg"

[blackfriday]
	angledQuotes = false
	fractions = false
	extensions = ["laxHtmlBlocks"]
